sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t swither/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swither/docker-react -- --coverage
